### ISSUE TITLE
Detailgeometrie muss optional sein

### ISSUE THREAD

**Issue by beistehen** [sogis/ipw-validator#1]
https://github.com/sogis/ipw-validator/blob/31497138d39ea3e151d1a701df135b658cf2dcce/model/2022-03-10/VSADSSMINI_2020_LV95_Validierung_IPW_20220310.ili#L66-L68

Obiger Constraint entspricht nicht der Realität. Nicht jeder PAA-Knoten hat eine Detailgeometrie. Herkunft dieses Constraints?

**Comment by edigonzales** [comment]
Excelliste.

**Comment by edigonzales** [comment]
@beistehen Kann ich schliessen, oder?
