### ISSUE TITLE
Verarbeitung von mehreren XTF (private Organisationsliste)

### ISSUE THREAD

**Issue by beistehen** [sogis/ipw-validator#3]
Es sollte möglich sein, mehrere XTF an den IPW-Validator zu übergeben. Dann können private Organisationslisten zusammen mit den DSS Mini-Daten mitgeliefert werden. Ansonsten gibt es Fehlermeldungen (fehlende Referenz-TID).

#### Vorschlag
Separates, zweites Input-Feld (markiert als "optional"), wo man eine Organisationsliste (XTF) aus dem Dateisystem auswählen kann.

_(Der VSA-Checker erwartet die private Organisationsliste zusammen mit den Daten in einem .zip. Das ist zwar praktisch, jedoch aus UI-Sicht für den Anwender schlecht, da er nicht darauf hingewiesen wird, allenfalls eine eigene, private Liste mitzusenden.)_

**Comment by edigonzales** [comment]
Sollte die Org-Liste nicht relativ statisch sein? Dann könnte man sie einfach auf dem Server hinterlegen.

Zweites Input-Feld müsste ich schauen, da Websocket-Transfer die Sache bissle exotischer macht.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Stefan Henrich ***@***.***>
Sent: Tuesday, July 12, 2022 11:37:17 AM
To: sogis/ipw-validator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sogis/ipw-validator] Verarbeitung von mehreren XTF (private Organisationsliste) (Issue #3)


Es sollte möglich sein, mehrere XTF an den IPW-Validator zu übergeben. Dann können private Organisationslisten zusammen mit den DSS Mini-Daten mitgeliefert werden. Ansonsten gibt es Fehlermeldungen (fehlende Referenz-TID).

Vorschlag

Separates, zweites Input-Feld (markiert als "optional"), wo man eine Organisationsliste (XTF) aus dem Dateisystem auswählen kann.

(Der VSA-Checker erwartet die private Organisationsliste zusammen mit den Daten in einem .zip. Das ist zwar praktisch, jedoch aus UI-Sicht für den Anwender schlecht, da er nicht darauf hingewiesen wird, allenfalls eine eigene, private Liste mitzusenden.)

**Comment by beistehen** [comment]
Gemäss Entscheid PL wird vorläufig beim Upload auf die IPW erwartet, dass alle referenzierten Organisationen in der Organisationsliste des VSA enthalten sind. Es wird keine Möglichkeit zum Upload von privaten Organisationslisten angeboten.

Somit müssen also vor dem Upload alle Referenzen auf eine private Organisationsliste durch den Lieferanten (manuell oder automatisiert) auf die TID "ch20p3q400000094" = "Sammelorganisation für alle privaten Eigentümer" geändert werden.
