### ISSUE TITLE
Google Spreadsheet in README nicht mehr verfügbar

### ISSUE THREAD

**Issue by beistehen** [sogis/ipw-validator#6]
https://github.com/sogis/ipw-validator/blob/5008ac9188367395e6107445e4ad55268daf2ea1/README.md?plain=1#L4-L6

Wo ist letzter Stand?

**Comment by edigonzales** [comment]
@beistehen Mmmh, hab aufgeräumt im Google Docs. Wahrscheinlich hab' ichs gekilled. Oh und den Papierkorb habe ich auch gelöscht. Mist. Wohl gone with the wind. Jetzt müsste man wohl Reto fragen und dann mittels ili-Model das Excelfile nachführen.
